// Every place the manual picker offers, and the nearest-known-city lookup
// the place label uses. Pure data + maths — no Expo imports — so it can be
// unit-tested under node; mobile/src/lib/location.ts re-exports it.

import { NRW_CITIES, type City } from "@shared/cities";

/**
 * Every place the manual picker offers: the curated NRW list first (the
 * website's ids, exact centroids Mohamed checked), then every German city or
 * town of 10,000+ from OpenStreetMap (mobile/src/lib/cities/germany.json,
 * generated by scripts/fetch-cities-germany.mjs). A generated entry within
 * 15 km of a curated one with the same name is the same place and is dropped.
 * Biggest first, so the picker's unfiltered top is Berlin, Hamburg, München…
 */
export const CITIES: City[] = mergeCities(
  NRW_CITIES,
  require("./germany.json") as City[],
);

/**
 * Case- and umlaut-insensitive key for a city name: "Münster" and "MUNSTER"
 * fold to the same thing. Only the German letters that differ from their
 * base are mapped; anything else is compared as-is.
 *
 * NOT `localeCompare(…, "de", { sensitivity: "base" })`. That was what this
 * did first, and on Hermes every such call goes out to Java's Collator over
 * JNI: 1,130 generated × 39 curated ≈ 44,000 calls at module load, each
 * allocating on the Java side — eighteen seconds of a busy JS thread and a
 * busy garbage collector before the first frame, on a Redmi Note 13. Folding
 * each name once is 1,170 string maps and no native calls at all.
 */
export function foldCityName(name: string): string {
  return name
    .toLowerCase()
    .replace(/ä/g, "a")
    .replace(/ö/g, "o")
    .replace(/ü/g, "u")
    .replace(/ß/g, "ss");
}

function mergeCities(curated: City[], generated: City[]): City[] {
  const out = [...curated];
  const curatedKeys = curated.map((c) => foldCityName(c.name));
  for (const g of generated) {
    const key = foldCityName(g.name);
    let dup = false;
    for (let i = 0; i < curated.length; i++) {
      const c = curated[i];
      // Distance first — it is the cheap check and rules out nearly all pairs.
      if (haversineKm(c.latitude, c.longitude, g.latitude, g.longitude) >= 15) continue;
      if (curatedKeys[i] === key) {
        dup = true;
        break;
      }
    }
    if (!dup) out.push(g);
  }
  return out.sort((a, b) => b.population - a.population);
}

export function nearestCity(
  lat: number,
  lng: number,
): { city: City; km: number } | null {
  let best: { city: City; km: number } | null = null;
  for (const city of CITIES) {
    const km = haversineKm(lat, lng, city.latitude, city.longitude);
    if (!best || km < best.km) best = { city, km };
  }
  return best;
}

function haversineKm(
  aLat: number,
  aLng: number,
  bLat: number,
  bLng: number,
): number {
  const R = 6371;
  const rad = (x: number) => (x * Math.PI) / 180;
  const dLat = rad(bLat - aLat);
  const dLng = rad(bLng - aLng);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(aLat)) * Math.cos(rad(bLat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

