// Germany-wide mosque locator data.
//
// The dataset (germany.json) is generated by scripts/fetch-mosques-germany.mjs
// straight from OpenStreetMap — see that script for how it is shaped. This
// module only adds distance: haversine from wherever the app currently
// thinks the user is (mobile/src/lib/place-context.tsx).
//
// The JSON is loaded with a lazy `require` inside nearestMosques rather than
// a top-level import, so screens that never open the mosque locator (the
// Times screen, above all — it is the one screen opened every single time)
// never pull roughly 1,600 mosque records into their module graph.

export interface Mosque {
  id: string;
  /** Falls back through name → name:de → name:ar → name:tr → operator while
   *  the data is generated; null when OSM had none of those but did have an
   *  addr:city, which is still enough to show and navigate to. */
  name: string | null;
  /** Present only when OSM carried a name:ar tag. */
  nameAr?: string;
  lat: number;
  lng: number;
  city: string | null;
  /** Street + house number, when OSM had both. */
  street?: string;
}

export interface MosqueWithDistance extends Mosque {
  /** Great-circle distance from the query point, in metres. */
  distanceMeters: number;
}

const EARTH_RADIUS_M = 6_371_000;

function haversineMeters(
  aLat: number,
  aLng: number,
  bLat: number,
  bLng: number,
): number {
  const rad = (x: number) => (x * Math.PI) / 180;
  const dLat = rad(bLat - aLat);
  const dLng = rad(bLng - aLng);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(aLat)) * Math.cos(rad(bLat)) * Math.sin(dLng / 2) ** 2;
  return 2 * EARTH_RADIUS_M * Math.asin(Math.sqrt(s));
}

function loadMosques(): Mosque[] {
  return require("./germany.json") as Mosque[];
}

/** The `limit` nearest mosques to a point, closest first. */
export function nearestMosques(
  lat: number,
  lng: number,
  limit = 25,
): MosqueWithDistance[] {
  const mosques = loadMosques();
  const withDistance: MosqueWithDistance[] = mosques.map((m) => ({
    ...m,
    distanceMeters: haversineMeters(lat, lng, m.lat, m.lng),
  }));
  withDistance.sort((a, b) => a.distanceMeters - b.distanceMeters);
  return withDistance.slice(0, limit);
}

export interface FormattedDistance {
  value: string;
  unit: "m" | "km";
}

/**
 * Splits a metre distance into a value + unit so the UI can localize both —
 * digits through toArabicIndic, and the unit through the strings table
 * (distanceMeters / distanceKm) rather than a hardcoded "m"/"km" in a
 * component.
 */
export function formatDistance(meters: number): FormattedDistance {
  if (meters < 1000) {
    return { value: String(Math.round(meters)), unit: "m" };
  }
  const km = meters / 1000;
  // One decimal below 10 km (e.g. "3.4"), whole numbers above (e.g. "42").
  const value = km < 10 ? km.toFixed(1) : String(Math.round(km));
  return { value, unit: "km" };
}
